name: optimus_network_inspector
description: Http inspector / logger for Http package. This package would allow you to log every Http request, response, and error from Http.
version: 1.0.3
homepage: https://gtech.digital

environment:
  sdk: ^3.8.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  sqflite: ^2.4.2
  provider: ^6.1.5+1
  intl: ^0.20.2
  collection: ^1.19.1
  share_plus: ^12.0.0

dev_dependencies:
  flutter_lints: 
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/json/
