name: network_inspector
description: Http inspector / logger for Dio and Http package. This package would allow you to log every Http request, response, and error from Dio & Http.
version: 1.2.1+2
homepage: https://github.com/Meruya-Techhnology/network_inspector

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  http: 
  sqflite: 
  provider: 
  intl: 
  analyzer: 
  collection: 
  share_plus: 

dev_dependencies:
  flutter_lints: 
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/json/
